### ISSUE TITLE
How to make Vale spellchecker suggest alternatives?

### ISSUE THREAD

**Issue by tbazant** [ChrisChinchilla/vale-vscode#15]
i have the following rule:
```
extends: spelling
message: "'%s' is a typo!"
dicpath: /home/toba/devel/suse-documentation-dicts/build
append: true
custom: true
dictionaries:
  - en_US-suse-doc
ignore:
  - SpellingIgnorelist.txt
action:
  name: suggest
```
how do i make it suggest alternatives to mispelled words after hitting CTRL+. in VSCode based on the specified distionaries?

**Comment by tbazant** [comment]
BTW the workds in the specified list `en_US-suse-doc` are recognized fine, there are just no suggestions

**Comment by ChrisChinchilla** [comment]
@tbazant Do you have somewhere I can reproduce the dictionary file and ignore list?

**Comment by ChrisChinchilla** [comment]
@tbazant Any follow up on my above comment?

**Comment by tbazant** [comment]
obsoloted, sorry for the delay
