### ISSUE TITLE
 Section overrides not working in editor

### ISSUE THREAD

**Issue by edouard-lopez** [ChrisChinchilla/vale-vscode#16]
related: https://github.com/errata-ai/vale-vscode/issues/70

## Config
I'm trying to disable Vale on my `package.json` with the following config in the `.vale.ini`:

```
[*]
BasedOnStyles = Vale, write-good

[package.json]
Vale.Spelling = NO
```

## CLI is OK
It does work with the CLI: 

```
❯ vale --config=./.vale.ini package.json
✔ 0 errors, 0 warnings and 0 suggestions in 1 file.
```

## Extension is NOT

But with the extension, I still got the error
![image](https://github.com/ChrisChinchilla/vale-vscode/assets/1212392/1ffe7199-0040-46b5-86e2-1f1fd95b74a1)

**Comment by ChrisChinchilla** [comment]
@edouard-lopez Do you still have this issue? I can't reproduce it…

**Comment by edouard-lopez** [comment]
Not anymore, but we switch to `3.x`

```
❯ vale --version
vale version 3.0.5
```

With Vale VSCode `v0.18.4`
