### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by thernstig** [ChrisChinchilla/vale-vscode#17]
When editing a markdown file with only 300 lines, if some text is marked with yellow squiggly lines (breaking some Vale rule), and then editing it, it takes takes 3-5 seconds before the yellow squiggly line is removed.

In short it seems the entire procedure to check files takes a long time.

I know there is a vale-lsp written in Rust https://github.com/errata-ai/vale-ls, and from my perspective that should be super-fast in doing the parsing (due to the fact it is written in Rust).

No other linter that scans files far larger than our markdown files is this slow. For example the Python linter Ruff (written in Rust, https://docs.astral.sh/ruff/) lints a file with thousands of lines in a millisecond basically.

Something is wrong "somewhere" but I do not know where in the Vale toolchain.

**Comment by ChrisChinchilla** [comment]
@thernstig As far as I can tell from people using the beta version, the next release out today, should fix a lot of this. Switching to using the language server is on the list, but as that's a reasonable amount of work, it will take me a little more time.

**Comment by prologic** [comment]
Just wanted to drop a note in here to say that for very large repos, there appears to be similar performance issues, but in the order of 10s or seconds to minutes.

**Comment by ChrisChinchilla** [comment]
@prologic Have you upgraded to the latest versions? As mentioned? If not, could you please open a new issue with a bit more detail about what you mean by "very large" and preferably some kind of reproducible repo for testing :)

**Comment by prologic** [comment]
Yup!
