### ISSUE TITLE
Start using a CHANGELOG

### ISSUE THREAD

**Issue by thernstig** [ChrisChinchilla/vale-vscode#19]
Looking here in Github:

![image](https://github.com/ChrisChinchilla/vale-vscode/assets/30827238/8811b0a3-a161-45b2-9ac3-c231938c88cd)

It has no information about what is included in each release. Could it be added?

Compare with something like:
https://github.com/errata-ai/vale/releases
https://github.com/microsoft/playwright/releases

**Comment by ChrisChinchilla** [comment]
@thernstig Ah sorry, i thought this was happening, will manually add some for the last couple of releases and also tweak the automated job to do this moving forward.
