### ISSUE TITLE
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by erinmirecki** [ChrisChinchilla/vale-vscode#29]
I have vale cli version 3.1.0 installed and when I try to view the errors for a file I get the following error

```
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
```

When I run `vale ls-config --output=JSON` I get the following

```
{
  "BlockIgnores": {},
  "Checks": null,
  "Formats": {},
  "Asciidoctor": {},
  "FormatToLang": {},
  "GBaseStyles": [
    "Vale"
  ],
  "GChecks": {},
  "IgnoredClasses": null,
  "IgnoredScopes": null,
  "MinAlertLevel": 2,
  "Vocab": null,
  "RuleToLevel": {},
  "SBaseStyles": {},
  "SChecks": {},
  "SkippedScopes": null,
  "Stylesheets": {},
  "TokenIgnores": {},
  "WordTemplate": "",
  "RootINI": "/path/to/.vale.ini",
  "Paths": [
    "/path/to/global/styles",
    "/path/to/local/styles"
  ],
  "ConfigFiles": [
    "/path/to/.vale.ini"
  ],
  "NLPEndpoint": ""
}
```

It looks like the StylesPath field was removed from Config recently (https://github.com/errata-ai/vale/commit/36157396c86d6449d5f357229f4c19c8d98087be#diff-c191ffc22fa5a135ce6bc8f03cc8314de6dec5e0330d6b89f47b9e49bfb00055)

**Comment by erinmirecki** [comment]
I'm running v0.18.5 of the Vale VSCode plugin and Vale 3.1.0. I'm running VSCode and Vale on Ubuntu 22.04.2 (WSL2). I don't think I have any special configuration, this is the first time installing both the Vale and the VSCode plugin. I modified the Vale > Vale CLI: Path setting on the VSCode extension to the absolute path to the Vale binary.

I'm not able to see the Vale linting alerts in the VSCode detailed problems view as described in the plugin feature details. I'm able to successfully run the Vale CLI and get a list of lint errors for the files in the repository.

**Comment by erinmirecki** [comment]
I didn't change anything and now the linting errors are showing up under problems and no errors.

**Comment by ChrisChinchilla** [comment]
@erinmirecki Hmm, it could be that it updated and VSCode wanted a refresh; when it wants that has always been a bit of a mystery. For now, I will close this unless anyone else experiences something similar.
