### ISSUE TITLE
Extenion isn't working with newest version of Vale, 3.3.0

### ISSUE THREAD

**Issue by maxhoriba** [ChrisChinchilla/vale-vscode#30]
Current local version of Vale is 2.28.2. 

Today, I tried upgrading my local version of Vale to 3.3.0, and the extension stopped working. 

Current version of extension I'm using: 
![image](https://github.com/ChrisChinchilla/vale-vscode/assets/136829683/af257051-d315-4808-a96e-59cf883c4771)

**Comment by ChrisChinchilla** [comment]
@maxhoriba Hmm, everyone else with the latest versions now has this working. Can you try quitting VScode and reopening it? Just to be sure?

**Comment by maxhoriba** [comment]
> @maxhoriba Hmm, everyone else with the latest versions now has this working. Can you try quitting VScode and reopening it? Just to be sure?

Definitely isn't working. I tried upgrading, disabling the extension, closing VS Code, then opening again, which didn't work. Downgraded back to 2.28.2 and it works again.

**Comment by ChrisChinchilla** [comment]
@maxhoriba No one else seems to be having this issue. So could you give me some extra details…

- Do you see any Vale-related output in _Help > Toggle Developer Tools > Console_
- What OS are you using?
- Your `vale ls-config` output
- A screenshot of the config of the extension.

**Comment by ChrisChinchilla** [comment]
@maxhoriba 

> Runtime error 'config\vocabularies/my-own-rules' directory does not exist


Definately looks concerning to me! Does Vale work if you run from command line in the same directory?

**Comment by maxhoriba** [comment]
> @maxhoriba
> 
> > Runtime error 'config\vocabularies/my-own-rules' directory does not exist
> 
> Definately looks concerning to me! Does Vale work if you run from command line in the same directory?

It doesn't! I tried and I get the same error when I run a command, for example: vale my-topic.md. Vale still works for 2.28.2...

**Comment by maxhoriba** [comment]
Fixed the issue locally. Closing this now
