### ISSUE TITLE
Server process exited with code 101

### ISSUE THREAD

**Issue by DanRoscigno** [ChrisChinchilla/vale-vscode#48]
- OS: mac 14.6.1
- chip: M2 Pro
- VSCode Insiders:
  -  Version: 1.93.0-insider
  - Commit: e2b54301a5745870f6b95d81c91fb3e9557d4f08
  - Date: 2024-08-20T08:04:15.567Z (7 hrs ago)
- Vale: Preview, installed on 2024-08-20, 09:21:37

Error: (I had a bunch of these)
```
[Info  - 10:52:27 AM] initialized!
thread 'main' panicked at src/server.rs:318:61:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Error - 10:52:28 AM] Server process exited with code 101.
[Info  - 10:52:28 AM] Connection to server got closed. Server will restart.
```

I restarted VS Code and Vale was working again. I worked for a while, and had no problems. I just now opened a new Markdown doc, and was clicking through the problems list. After clicking a few, I saw another crash.

## Question

Do you know how I can run with `RUST_BACKTRACE=1`, and do you want me to try that?

**Comment by jdkato** [comment]
This should be fixed in the next release of `vale-ls`, https://github.com/errata-ai/vale-ls/issues/12.

**Comment by ChrisChinchilla** [comment]
Updated in the latest pre-release 0.23.3
