### ISSUE TITLE
Publish the extension to Open VSX

### ISSUE THREAD

**Issue by filiptronicek** [ChrisChinchilla/vale-vscode#5]
Hello there 👋,
I would like to kindly ask you to publish this extension to the Open VSX marketplace.

## Context

Unfortunately, as Microsoft prohibits usages of the Microsoft marketplace by any other products or redistribution of `.vsix` files from it, in order to use VS Code extensions in non-Microsoft products, we kindly ask that you take ownership of the VS Code extension namespace in [Open VSX](https://open-vsx.org/) and publish this extension on Open VSX.

## What is Open VSX? Why does it exist?

Open VSX is a vendor neutral alternative to the MS marketplace used by most other derivatives of VS Code like [VSCodium](https://vscodium.com/), [Gitpod](https://www.gitpod.io), [OpenVSCode](https://github.com/gitpod-io/openvscode-server), [Theia](https://theia-ide.org/)-based IDEs, and so on.

You can read on about Open VSX at the Eclipse Foundation's [Open VSX FAQ](https://www.eclipse.org/legal/open-vsx-registry-faq/).

## How can you publish to Open VSX?

The docs to publish an extension can be found [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions). This process is straightforward and shouldn't take too long. Essentially, you need an authentication token and to execute the `ovsx publish` command to publish your extension. There's also [a doc](https://github.com/open-vsx/publish-extensions/blob/master/docs/direct_publish_setup.md) explaining the whole process with an example GitHub Action workflow.

https://github.com/errata-ai/vale-vscode had been published to https://open-vsx.org previously, so it would be great for users to migrate over from the deprecated one.

**Comment by tbazant** [comment]
i can take care of that, but it's gonna be under my personal access token and i am not sure you want this ?!

**Comment by ChrisChinchilla** [comment]
@tbazant First… Sorry, I don't seem to have been getting any issue notifications on the repo and missed all these issues, will get on top of them.

Also @filiptronicek There is an action that does this already (https://github.com/ChrisChinchilla/vale-vscode/actions/workflows/build.yaml), but it seems to have been failing, again I wasn't getting notifications, will fix.

**Comment by ChrisChinchilla** [comment]
This is in progress, waiting for namespace verification.
