### ISSUE TITLE
Vale VSCode takes several seconds to react

### ISSUE THREAD

**Issue by Makki93** [ChrisChinchilla/vale-vscode#9]
<img width="617" alt="image" src="https://github.com/ChrisChinchilla/vale-vscode/assets/44347047/3ad06ead-0620-4d56-9689-a5552cc89d22">

vale version 2.26.0 (via pip) and 2.28.1 tested. Seems to be a problem of the extension.

**Comment by ChrisChinchilla** [comment]
Hey @Makki93 can you give me a bit more detail here, the screenshot isn't telling me much. Takes time to react how? When you do what?

And what OS are you using?

**Comment by Makki93** [comment]
Hi,
sorry for the short description.
I don't know where the issue actually comes from, but for instance, when I search and replace globally with multiple files open in VS Code, then this dialog pops up, and it usually takes several seconds to disappear again. In this timeframe, I can't modify the opened files.

I am Using macOS Ventura 13.6

**Comment by ChrisChinchilla** [comment]
@Makki93 Sorry I forgo9t about things my notifications were messed up for a while, but it seems like this might be related to #13 

Could you give me some of the same details as supplied in that issue? So…

OS version
VSCode version
Vale VSCode extension version
Vale version
Intel or Apple Silicon?
How much memory do you have?
How did you install vale?

**Comment by ChrisChinchilla** [comment]
Scrap that, I've figured out what's doing this. Going to close this in favour of other issue anyway.
